DEPS :=  \
	 mlibc-headers \
	 tc-autoconf \
	 tc-autoconf-2.69 \
	 tc-automake \
	 tc-libtool \
	 tc-gcc \
	 mlibc-libraries \
	 libgcc

VERSION := dummy
URLS := 

.PHONY: build
build:
	@echo "Definitely building"

.PHONY: clean
clean:
	@echo "Definitely cleaning"

.PHONY: prepare-rebuild
prepare-rebuild:
	@echo "Definitely preparing rebuild"

.PHONY: get-deps
get-deps:
	@echo $(DEPS)

.PHONY: get-version
get-version:
	@echo $(VERSION)

.PHONY: get-urls
get-urls:
	@echo $(URLS)

#.PHONY: get-source-dir
#get-source-dir:
#	@echo ""

#.PHONY: use-source-dir-of
#use-source-dir-of:
#	@echo ""

